name = input("Enter your name:\n")
age = input("Enter your age:\n")
class_name = input("Enter your class:\n")
college = input("Enter your college:\n")
b_grp = input("What's your blood group:\n")
print("Name:", name)
print("Age:", age)
print("Class:", class_name)
print("College:", college)
print("Blood Group:", b_grp)
